# Generated by Django 5.0.7 on 2025-03-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Signed', 'Signed'), ('Rejected', 'Rejected')], default='Draft', max_length=25),
        ),
    ]
