# Generated by Django 5.0.7 on 2025-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_contract_company_account_contract_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company_oked',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
