# Generated by Django 5.0.7 on 2025-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_contract_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default='2025-03-17', null=True),
        ),
    ]
