# Generated by Django 5.0.7 on 2025-03-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_contract_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
