version: "3.8"

services:
  telegram_bot:
    build:
      context: .
    container_name: telegram_bot
    env_file:
      - .env
    volumes:
      - ./config:/usr/src/app/
      - ./bot:/usr/src/app/bot
      - ./src:/usr/src/app/src
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static
      # - ./requirements.txt:/usr/src/app/requirements.txt
    depends_on:
      - eimzo
    command: python manage.py app
    restart: unless-stopped

  eimzo:
    build:
      context: ./didoxTokenGenerator  # This is the correct path for E-IMZO
      dockerfile: Dockerfile
    container_name: eimzo_service
    ports:
      - "8080:8080"
    volumes:
      - ./didoxTokenGenerator/keys:/app/keys  # Persist keys directory
      - ./didoxTokenGenerator/lib:/app/lib    # Persist libraries
    restart: unless-stopped
