# Generated by Django 5.0.7 on 2025-03-17 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('monthly_payment', models.CharField(max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('company_mfo', models.CharField(blank=True, max_length=15, null=True)),
                ('company_inn', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, default='17-03-2025', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='botapp.botuser')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
